name = "Tomorrow Night's Alright"
license = "MIT"
licenselink = "https://github.com/jmiahjones/tomorrow-nights-alright-hugo-theme/blob/main/LICENSE"
description = "Tomorrow Night's Alright is a simple Hugo theme based on the Hugo Piercer Theme and the Tomorrow Night color theme."
homepage = "https://github.com/jmiahjones/tomorrow-nights-alright-hugo-theme/"
tags = ["blog", "responsive", "minimal", "simple", "font awesome", "dark", "landing page", "contact form", "mobile", "fast", "customizable", "google fonts"]
features = [
  "customizable (color palette, font size, font family and more)",
  "hamburger menu without JavaScript",
  "great SEO by default",
  "mobile-first philosophy",
  "fast",
]
min_version = "0.41"

[author]
  name = "Jeremiah Jones"
